version: "3.8"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./test-dump.sql:/db/test-dump.sql
      - ./db-dump-init.sh:/docker-entrypoint-initdb.d/db-dump-init.sh
    ports:
      - 5432:5432
  
  app:
    image: test
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3000:3000

